server:
  port: 8089
  context-path: /boot_ems
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/maven
    username: root
    password: root
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    encoding:
      charset: UTF-8
      force: true
mybatis:
  mapper-locations: classpath:com/baizhi/hlp/mapper/*Mapper.xml
  type-aliases-package: com.baizhi.hlp.entity